<a href="https://colab.research.google.com/github/zackdihel/DA-project-1/blob/main/notebooks/01_Data_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
col_specs = [(0,3), (4,5), (6,7),(8,9), (10,11), (12,13), (14,15),(16,17),(18,19),
             (20,21),(22,24),(25,30),(31,36),(37,42),(43,48),(49,54),(55,60),(61,62),
             (63,68),(69,70),(71,76),(77,82),(83,88),(89,94),(95,100),(101,103),(104,106),
             (107,108),(109,110),(111,117),(118,120),(121,126),(127,132),(133,138),
             (139,144),(145,150),(151,156),(157,158),(159,160),(161,166),(167,172),
              (173,178),(179,184),(185,190),(191,193),(194,196)
            ]
col_name = ['Store ID', 'Chain', 'Co-owned', 'State', 'South NJ', 'Central NJ', 'North NJ',
            'Phil. suburb', 'Easton','NJ Shore','Num. Callbacks','FT Empl.','PT Empl.',
            'Num. Mgrs','Starting Wage','Months to Raise','Raise increase ($/hr)','Bonus',
            '% affected by Min Wage','Free/Reduced meals','Opening Hour','Operating hours',
            'P_Soda','P_Fry','P_Entree','Num. Registers','Num. Registers at 11am',
            'Type 2nd Interview','Status 2nd Interview', 'Date 2nd Interview','Num. Callbacks_2',
            'FT Empl._2','PT Empl._2','Num. Mgrs_2','Starting Wage_2','Months to Raise_2',
            'Raise increase ($/hr)_2','Special Program_2','Free/Reduced meals_2',
            'Opening Hour_2','Operating hours_2','P_Soda_2','P_Fry_2','P_Entree_2',
            'Num. Registers_2','Num. Registers at 11am_2'
            ]

df_raw = pd.read_fwf('https://raw.githubusercontent.com/zackdihel/DA-project-1/refs/heads/main/data/raw/public.dat',
                     colspecs= col_specs, names=col_name)
df_raw.head()

,Store ID,Chain,Co-owned,State,South NJ,Central NJ,North NJ,Phil. suburb,Easton,NJ Shore,...,Raise increase ($/hr)_2,Special Program_2,Free/Reduced meals_2,Opening Hour_2,Operating hours_2,P_Soda_2,P_Fry_2,P_Entree_2,Num. Registers_2,Num. Registers at 11am_2
0,46,1,0,0,0,0,0,1,0,0,...,0.08,1,2,6.50,16.50,1.03,.,0.94,4,4
1,49,2,0,0,0,0,0,1,0,0,...,0.05,0,2,10.00,13.00,1.01,0.89,2.35,4,4
2,506,2,1,0,0,0,0,1,0,0,...,0.25,.,1,11.00,11.00,0.95,0.74,2.33,4,3
3,56,4,1,0,0,0,0,1,0,0,...,0.15,0,2,10.00,12.00,0.92,0.79,0.87,2,2
4,61,4,1,0,0,0,0,1,0,0,...,0.15,0,2,10.00,12.00,1.01,0.84,0.95,2,2

Codes:

Free/reduced Meal Variable:
0 = none
1 = free meals
2 = reduced price meals
3 = both free and reduced price meals


Second Interview Status
0 = refused second interview (count = 1)
1 = answered 2nd interview (count = 399)
2 = closed for renovations (count = 2)
3 = closed "permanently" (count = 6)
4 = closed for highway construction (count = 1)
5 = closed due to Mall fire (count = 1)


*Note: number of call-backs = 0 if contacted on first call

In [3]:
df_raw.to_csv('datatable.csv', index=False)

In [5]:
df_raw.describe()

,Store ID,Chain,Co-owned,State,South NJ,Central NJ,North NJ,Phil. suburb,Easton,NJ Shore,Num. Callbacks,Bonus,Free/Reduced meals,Opening Hour,Operating hours,Type 2nd Interview,Status 2nd Interview,Date 2nd Interview
count,410.000000,410.000000,410.000000,410.000000,410.000000,410.000000,410.000000,410.000000,410.000000,410.000000,410.000000,410.000000,410.000000,410.000000,410.000000,410.000000,410.000000,410.000000
mean,246.507317,2.117073,0.343902,0.807317,0.226829,0.153659,0.426829,0.087805,0.104878,0.085366,1.141463,0.246341,1.907317,8.041463,14.439024,1.095122,1.048780,112398.826829
std,148.231799,1.110497,0.475589,0.394888,0.419293,0.361062,0.495221,0.283357,0.306771,0.279767,1.386095,0.431406,0.533655,2.160885,2.809987,0.293742,0.353205,3118.531758
min,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,7.000000,1.000000,0.000000,110592.000000
25%,119.250000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,6.500000,12.000000,1.000000,1.000000,111192.000000
50%,237.500000,2.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,7.000000,15.500000,1.000000,1.000000,111392.000000
75%,371.750000,3.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,2.000000,0.000000,2.000000,10.500000,16.000000,1.000000,1.000000,111792.000000
max,522.000000,4.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,8.000000,1.000000,3.000000,11.500000,24.000000,2.000000,5.000000,123192.000000

In [6]:
df_raw.isna().sum()

Store ID                    0
Chain                       0
Co-owned                    0
State                       0
South NJ                    0
Central NJ                  0
North NJ                    0
Phil. suburb                0
Easton                      0
NJ Shore                    0
Num. Callbacks              0
FT Empl.                    0
PT Empl.                    0
Num. Mgrs                   0
Starting Wage               0
Months to Raise             0
Raise increase ($/hr)       0
Bonus                       0
% affected by Min Wage      0
Free/Reduced meals          0
Opening Hour                0
Operating hours             0
P_Soda                      0
P_Fry                       0
P_Entree                    0
Num. Registers              0
Num. Registers at 11am      0
Type 2nd Interview          0
Status 2nd Interview        0
Date 2nd Interview          0
Num. Callbacks_2            0
FT Empl._2                  0
PT Empl._2                  0
Num. Mgrs_2                 0
Starting Wage_2             0
Months to Raise_2           0
Raise increase ($/hr)_2     0
Special Program_2           0
Free/Reduced meals_2        0
Opening Hour_2              0
Operating hours_2           0
P_Soda_2                    0
P_Fry_2                     0
P_Entree_2                  0
Num. Registers_2            0
Num. Registers at 11am_2    0
dtype: int64