<a href="https://colab.research.google.com/github/zackdihel/DA-project-1/blob/main/notebooks/02_Replication.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("datatable.csv")
df

,Store ID,Chain,Co-owned,State,South NJ,Central NJ,North NJ,Phil. suburb,Easton,NJ Shore,...,Raise increase ($/hr)_2,Special Program_2,Free/Reduced meals_2,Opening Hour_2,Operating hours_2,P_Soda_2,P_Fry_2,P_Entree_2,Num. Registers_2,Num. Registers at 11am_2
0,46,1,0,0,0,0,0,1,0,0,...,0.08,1,2,6.50,16.50,1.03,.,0.94,4,4
1,49,2,0,0,0,0,0,1,0,0,...,0.05,0,2,10.00,13.00,1.01,0.89,2.35,4,4
2,506,2,1,0,0,0,0,1,0,0,...,0.25,.,1,11.00,11.00,0.95,0.74,2.33,4,3
3,56,4,1,0,0,0,0,1,0,0,...,0.15,0,2,10.00,12.00,0.92,0.79,0.87,2,2
4,61,4,1,0,0,0,0,1,0,0,...,0.15,0,2,10.00,12.00,1.01,0.84,0.95,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
405,423,2,1,1,0,0,1,0,0,0,...,0.50,0,1,11.00,11.00,1.05,0.84,2.32,3,2
406,424,2,1,1,0,0,1,0,0,0,...,0.50,0,1,11.00,14.00,1.05,0.94,2.32,5,3
407,426,3,1,1,0,0,1,0,0,0,...,0.25,1,2,6.00,18.00,1.11,1.05,1.05,6,5
408,427,4,0,1,0,0,1,0,0,0,...,.,1,2,10.50,12.50,1.11,1.09,2.07,2,2
409,428,4,0,1,0,0,1,0,0,0,...,0.10,0,2,10.50,12.50,1.05,0.89,2.11,2,2

In [3]:
df_filter = df.drop(columns=['Chain','Num. Registers','Num. Registers_2','Num. Registers at 11am','Num. Registers at 11am_2',
                 'Opening Hour','Opening Hour_2', 'Operating hours','Operating hours_2',
                 'Num. Callbacks_2','Num. Callbacks','Num. Mgrs','Num. Mgrs_2','Free/Reduced meals',
                 'Free/Reduced meals_2','Date 2nd Interview','Type 2nd Interview','Special Program_2',
                 'Co-owned','South NJ','Central NJ','Phil. suburb','Easton','NJ Shore','North NJ'])
df_filter

,Store ID,State,FT Empl.,PT Empl.,Starting Wage,Months to Raise,Raise increase ($/hr),Bonus,% affected by Min Wage,P_Soda,...,P_Entree,Status 2nd Interview,FT Empl._2,PT Empl._2,Starting Wage_2,Months to Raise_2,Raise increase ($/hr)_2,P_Soda_2,P_Fry_2,P_Entree_2
0,46,0,30.00,15.00,.,19.0,.,1,.,1.03,...,0.52,1,3.50,35.00,4.30,26.0,0.08,1.03,.,0.94
1,49,0,6.50,6.50,.,26.0,.,0,.,1.01,...,2.35,1,0.00,15.00,4.45,13.0,0.05,1.01,0.89,2.35
2,506,0,3.00,7.00,.,13.0,0.37,0,30.0,0.95,...,2.33,1,3.00,7.00,5.00,19.0,0.25,0.95,0.74,2.33
3,56,0,20.00,20.00,5.00,26.0,0.10,1,0.0,0.87,...,1.79,1,0.00,36.00,5.25,26.0,0.15,0.92,0.79,0.87
4,61,0,6.00,26.00,5.50,52.0,0.15,1,0.0,0.87,...,1.65,1,28.00,3.00,4.75,13.0,0.15,1.01,0.84,0.95
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
405,423,1,2.00,10.00,4.95,13.0,0.50,1,33.0,1.06,...,2.34,1,19.00,3.50,5.25,13.0,0.50,1.05,0.84,2.32
406,424,1,3.50,6.50,4.75,13.0,0.25,0,45.0,1.06,...,2.34,1,12.00,3.00,5.25,19.0,0.50,1.05,0.94,2.32
407,426,1,3.00,33.00,4.25,26.0,0.15,0,75.0,1.18,...,1.06,1,5.00,25.00,5.05,19.0,0.25,1.11,1.05,1.05
408,427,1,7.00,8.00,4.75,13.0,0.10,0,40.0,1.06,...,2.03,1,0.00,35.00,5.05,.,.,1.11,1.09,2.07
409,428,1,0.00,33.00,4.62,13.0,0.12,0,100.0,1.06,...,1.06,1,10.00,24.00,5.14,13.0,0.10,1.05,0.89,2.11

'State' = 0 PA, 1 NJ;
'Status 2nd Interview' = 0 refused, 1 accepted, 2-5 closed

In [4]:
df_filter = df_filter.dropna()

In [5]:
df_filter['state_label'] = df_filter['State'].map({0: 'PA', 1: 'NJ'})
df_filter = df_filter.rename(columns={
    'FT Empl.' : 'FT_Empl',
    'FT Empl._2' :'FT_Empl_2',
    'Starting Wage' : 'Wage',
    'Starting Wage_2' : 'Wage_2'
})
df_filter

,Store ID,State,FT_Empl,PT Empl.,Wage,Months to Raise,Raise increase ($/hr),Bonus,% affected by Min Wage,P_Soda,...,Status 2nd Interview,FT_Empl_2,PT Empl._2,Wage_2,Months to Raise_2,Raise increase ($/hr)_2,P_Soda_2,P_Fry_2,P_Entree_2,state_label
0,46,0,30.00,15.00,.,19.0,.,1,.,1.03,...,1,3.50,35.00,4.30,26.0,0.08,1.03,.,0.94,PA
1,49,0,6.50,6.50,.,26.0,.,0,.,1.01,...,1,0.00,15.00,4.45,13.0,0.05,1.01,0.89,2.35,PA
2,506,0,3.00,7.00,.,13.0,0.37,0,30.0,0.95,...,1,3.00,7.00,5.00,19.0,0.25,0.95,0.74,2.33,PA
3,56,0,20.00,20.00,5.00,26.0,0.10,1,0.0,0.87,...,1,0.00,36.00,5.25,26.0,0.15,0.92,0.79,0.87,PA
4,61,0,6.00,26.00,5.50,52.0,0.15,1,0.0,0.87,...,1,28.00,3.00,4.75,13.0,0.15,1.01,0.84,0.95,PA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
405,423,1,2.00,10.00,4.95,13.0,0.50,1,33.0,1.06,...,1,19.00,3.50,5.25,13.0,0.50,1.05,0.84,2.32,NJ
406,424,1,3.50,6.50,4.75,13.0,0.25,0,45.0,1.06,...,1,12.00,3.00,5.25,19.0,0.50,1.05,0.94,2.32,NJ
407,426,1,3.00,33.00,4.25,26.0,0.15,0,75.0,1.18,...,1,5.00,25.00,5.05,19.0,0.25,1.11,1.05,1.05,NJ
408,427,1,7.00,8.00,4.75,13.0,0.10,0,40.0,1.06,...,1,0.00,35.00,5.05,.,.,1.11,1.09,2.07,NJ
409,428,1,0.00,33.00,4.62,13.0,0.12,0,100.0,1.06,...,1,10.00,24.00,5.14,13.0,0.10,1.05,0.89,2.11,NJ

In [23]:
df_filter = df_filter.replace('.', None)

In [25]:
df_filter = df_filter.dropna()
df_filter

,Store ID,State,FT_Empl,PT Empl.,Wage,Months to Raise,Raise increase ($/hr),Bonus,% affected by Min Wage,P_Soda,...,PT Empl._2,Wage_2,Months to Raise_2,Raise increase ($/hr)_2,P_Soda_2,P_Fry_2,P_Entree_2,state_label,Treat,Post
3,56,0,20.0,20.00,5.00,26.0,0.10,1,0.0,0.87,...,36.00,5.25,26.0,0.15,0.92,0.79,0.87,PA,0,1
4,61,0,6.0,26.00,5.50,52.0,0.15,1,0.0,0.87,...,3.00,4.75,13.0,0.15,1.01,0.84,0.95,PA,0,1
6,445,0,50.0,35.00,5.00,26.0,0.10,0,0.0,1.04,...,18.00,4.75,26.0,0.15,1.04,0.86,0.94,PA,0,1
7,451,0,10.0,17.00,5.00,52.0,0.25,0,0.0,1.05,...,9.00,5.00,26.0,0.20,1.11,0.84,0.94,PA,0,1
8,455,0,2.0,8.00,5.25,13.0,0.25,0,0.0,0.73,...,12.00,5.00,13.0,0.25,0.94,0.84,2.32,PA,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
405,423,1,2.0,10.00,4.95,13.0,0.50,1,33.0,1.06,...,3.50,5.25,13.0,0.50,1.05,0.84,2.32,NJ,1,1
406,424,1,3.5,6.50,4.75,13.0,0.25,0,45.0,1.06,...,3.00,5.25,19.0,0.50,1.05,0.94,2.32,NJ,1,1
407,426,1,3.0,33.00,4.25,26.0,0.15,0,75.0,1.18,...,25.00,5.05,19.0,0.25,1.11,1.05,1.05,NJ,1,1
408,427,1,7.0,8.00,4.75,13.0,0.10,0,40.0,1.06,...,35.00,5.05,None,None,1.11,1.09,2.07,NJ,1,1
409,428,1,0.0,33.00,4.62,13.0,0.12,0,100.0,1.06,...,24.00,5.14,13.0,0.10,1.05,0.89,2.11,NJ,1,1

In [26]:
cols = ['FT_Empl', 'Wage', 'P_Fry','P_Soda','P_Entree',
        'FT_Empl_2', 'Wage_2','P_Fry_2','P_Soda_2', 'P_Entree_2']

df_filter[cols] = df_filter[cols].apply(pd.to_numeric, errors='coerce')

In [27]:
#mean and std before NJ min wage increase
before = df_filter.groupby('state_label')[['FT_Empl', 'Wage', 'P_Fry','P_Soda','P_Entree']].agg(['mean','std'])
before

               FT_Empl                 Wage               P_Fry            \
                  mean        std      mean       std      mean       std
state_label
NJ            7.585551   7.289102  4.601293  0.341963  0.939886  0.102173
PA           10.774194  11.364194  4.669677  0.359676  0.846129  0.088473

               P_Soda            P_Entree
                 mean       std      mean      std
state_label
NJ           1.063384  0.084068  1.380532  0.67006
PA           0.976129  0.071571  1.244194  0.62625

In [28]:
#mean and std after NJ min wage increase
after = df_filter.groupby('state_label')[['FT_Empl_2', 'Wage_2', 'P_Fry_2','P_Soda_2','P_Entree_2']].agg(['mean','std'])
after

            FT_Empl_2              Wage_2             P_Fry_2            \
                 mean       std      mean       std      mean       std
state_label
NJ           8.152091  7.386654  5.077985  0.100359  0.957605  0.106337
PA           8.120968  8.884360  4.624032  0.363131  0.863387  0.098396

             P_Soda_2           P_Entree_2
                 mean       std       mean       std
state_label
NJ           1.063308  0.087733   1.438555  0.674487
PA           0.983871  0.055378   1.184194  0.571313

In [34]:
after.columns = before.columns

#Difference after wage change
diff = after - before
print(diff)

              FT_Empl                Wage               P_Fry            \
                 mean       std      mean       std      mean       std
state_label
NJ           0.566540  0.097552  0.476692 -0.241604  0.017719  0.004164
PA          -2.653226 -2.479834 -0.045645  0.003454  0.017258  0.009923

               P_Soda            P_Entree
                 mean       std      mean       std
state_label
NJ          -0.000076  0.003664  0.058023  0.004427
PA           0.007742 -0.016193 -0.060000 -0.054937

In [35]:
#difference between states
state_diff = diff.loc['NJ'] - diff.loc['PA']
print("\nDifference-in-Differences:")
print(state_diff)

Difference-in-Differences:
FT_Empl   mean    3.219766
          std     2.577386
Wage      mean    0.522337
          std    -0.245059
P_Fry     mean    0.000461
          std    -0.005759
P_Soda    mean   -0.007818
          std     0.019858
P_Entree  mean    0.118023
          std     0.059364
dtype: float64

In [37]:
#difference in means between NJ and PA following NJ's minimum wage increase
diff_means = diff.xs('mean', axis=1, level=1)
print(diff_means)

              FT_Empl      Wage     P_Fry    P_Soda  P_Entree
state_label
NJ           0.566540  0.476692  0.017719 -0.000076  0.058023
PA          -2.653226 -0.045645  0.017258  0.007742 -0.060000

In [38]:
#difference in std between NJ and PA following NJ's minimum wage increase
diff_std = diff.xs('std', axis=1, level=1)
print(diff_std)

              FT_Empl      Wage     P_Fry    P_Soda  P_Entree
state_label
NJ           0.097552 -0.241604  0.004164  0.003664  0.004427
PA          -2.479834  0.003454  0.009923 -0.016193 -0.054937

In [39]:
cols = ['Store ID','Treat','FT_Empl', 'Wage', 'P_Fry','P_Soda','P_Entree',
        'FT_Empl_2', 'Wage_2','P_Fry_2','P_Soda_2', 'P_Entree_2']

In [40]:
import statsmodels.formula.api as smf

df_filter['Treat'] = df_filter['State']
df_filter['Post'] = 1

before_df = df_filter[['Store ID', 'Treat', 'FT_Empl', 'Wage', 'P_Soda','P_Fry','P_Entree']].copy()
before_df['Post'] = 0
before_df = before_df.rename(columns={'P_Soda': 'Price_Soda',
                                      'P_Fry': 'Price_Fries','P_Entree': 'Price_Entree'})

after_df = df_filter[['Store ID', 'Treat', 'FT_Empl_2', 'Wage_2', 'P_Soda_2','P_Fry_2','P_Entree_2']].copy()
after_df['Post'] = 1
after_df = after_df.rename(columns={'FT_Empl_2': 'FT_Empl', 'Wage_2': 'Wage', 'P_Soda_2': 'Price_Soda',
                                      'P_Fry_2': 'Price_Fries','P_Entree_2': 'Price_Entree'})

df_combine = pd.concat([before_df, after_df])
df_combine

,Store ID,Treat,FT_Empl,Wage,Price_Soda,Price_Fries,Price_Entree,Post
3,56,0,20.0,5.00,0.87,0.82,1.79,0
4,61,0,6.0,5.50,0.87,0.77,1.65,0
6,445,0,50.0,5.00,1.04,0.88,0.94,0
7,451,0,10.0,5.00,1.05,0.84,0.96,0
8,455,0,2.0,5.25,0.73,0.73,2.32,0
...,...,...,...,...,...,...,...,...
405,423,1,19.0,5.25,1.05,0.84,2.32,1
406,424,1,12.0,5.25,1.05,0.94,2.32,1
407,426,1,5.0,5.05,1.11,1.05,1.05,1
408,427,1,0.0,5.05,1.11,1.09,2.07,1
409,428,1,10.0,5.14,1.05,0.89,2.11,1

In [41]:
print(df_combine['Post'].value_counts())

Post
0    325
1    325
Name: count, dtype: int64

In [42]:
df_combine = pd.concat([before_df, after_df], ignore_index=True).dropna().reset_index(drop=True)
cols_needed = ['FT_Empl', 'Wage', 'Price_Soda', 'Price_Fries', 'Price_Entree', 'Treat', 'Post', 'Store ID']
df_combine_clean = df_combine[cols_needed].dropna().reset_index(drop=True)

In [43]:
#OLS regression
for outcome in ['FT_Empl', 'Wage', 'Price_Soda', 'Price_Fries', 'Price_Entree']:
    #clusters std err
    model = smf.ols(f'{outcome} ~ Treat * Post', data=df_combine_clean).fit(
        cov_type='cluster',
        cov_kwds={'groups': df_combine_clean['Store ID']}
    )
    print(f"\n--- Regression: {outcome} ---")
    print(model.summary().tables[1])

--- Regression: FT_Empl ---
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     10.7742      1.437      7.497      0.000       7.958      13.591
Treat         -3.1886      1.505     -2.119      0.034      -6.139      -0.239
Post          -2.6532      1.729     -1.534      0.125      -6.043       0.736
Treat:Post     3.2198      1.816      1.773      0.076      -0.339       6.779
==============================================================================

--- Regression: Wage ---
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      4.6697      0.045    102.665      0.000       4.581       4.759
Treat         -0.0684      0.050     -1.367      0.172      -0.166       0.030
Post          -0.0456      0.050     -0.910      0.363      -0.144       0.053
Treat:Post     0.5223      0.054      9.683      0.000       0.417       0.628
==============================================================================

--- Regression: Price_Soda ---
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.9761      0.009    107.849      0.000       0.958       0.994
Treat          0.0873      0.010      8.348      0.000       0.067       0.108
Post           0.0077      0.009      0.891      0.373      -0.009       0.025
Treat:Post    -0.0078      0.010     -0.814      0.416      -0.027       0.011
==============================================================================

--- Regression: Price_Fries ---
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.8461      0.011     75.627      0.000       0.824       0.868
Treat          0.0938      0.013      7.233      0.000       0.068       0.119
Post           0.0173      0.008      2.105      0.035       0.001       0.033
Treat:Post     0.0005      0.009      0.050      0.960      -0.018       0.019
==============================================================================

--- Regression: Price_Entree ---
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      1.2442      0.079     15.710      0.000       1.089       1.399
Treat          0.1363      0.089      1.526      0.127      -0.039       0.311
Post          -0.0600      0.039     -1.523      0.128      -0.137       0.017
Treat:Post     0.1180      0.045      2.649      0.008       0.031       0.205
==============================================================================